In [2]:
import torch

def generate_data():
    # 本函数生成0-9，10个数字的图片矩阵
    image_data=[]
    num_0 = torch.tensor(
    [[0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [0,1,0,0,1,0],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_0)
    num_1 = torch.tensor(
    [[0,0,0,1,0,0],
    [0,0,1,1,0,0],
    [0,0,0,1,0,0],
    [0,0,0,1,0,0],
    [0,0,1,1,1,0],
    [0,0,0,0,0,0]])
    image_data.append(num_1)
    num_2 = torch.tensor(
    [[0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [0,0,0,1,0,0],
    [0,0,1,0,0,0],
    [0,1,1,1,1,0],
    [0,0,0,0,0,0]])
    image_data.append(num_2)
    num_3 = torch.tensor(
    [[0,0,1,1,0,0],
    [0,0,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_3)
    num_4 = torch.tensor(
    [
    [0,0,0,0,1,0],
    [0,0,0,1,1,0],
    [0,0,1,0,1,0],
    [0,1,1,1,1,1],
    [0,0,0,0,1,0],
    [0,0,0,0,0,0]])
    image_data.append(num_4)
    num_5 = torch.tensor(
    [
    [0,1,1,1,0,0],
    [0,1,0,0,0,0],
    [0,1,1,1,0,0],
    [0,0,0,0,1,0],
    [0,1,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_5)
    num_6 = torch.tensor(
    [[0,0,1,1,0,0],
    [0,1,0,0,0,0],
    [0,1,1,1,0,0],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_6)
    num_7 = torch.tensor(
    [
    [0,1,1,1,1,0],
    [0,0,0,0,1,0],
    [0,0,0,1,0,0],
    [0,0,0,1,0,0],
    [0,0,0,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_7)
    num_8 = torch.tensor(
    [[0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0],
    [0,0,0,0,0,0]])
    image_data.append(num_8)
    num_9 = torch.tensor(
    [
    [0,1,1,1,1,0],
    [0,1,0,0,1,0],
    [0,1,1,1,1,0],
    [0,0,0,0,1,0],
    [0,0,0,0,1,0],
    [0,0,0,0,0,0]])
    image_data.append(num_9)
    return image_data

image_data = generate_data()


In [3]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import cv2

In [25]:
# plt.hist(img_9.ravel(), 256, [0, 1])

In [74]:
def calcHamming(vector1, vector2):
    vector3 = np.nonzero(vector1 - vector2)
    count ,  = vector3[0].shape
    return count

def calcEulerDistance(vector1, vector2):
    return np.sqrt(np.sum(np.square(vector1-vector2)))

# for i in range(10):
#     for j in range(i+1, 10):
#         print(calcEulerDistance(features[i], features[j]))

In [109]:
num_0 = torch.tensor(
    [[0,0,0,0,0,0],
    [0,0,1,1,0,0],
    [0,1,0,0,1,0],
    [0,1,0,0,1,0],
    [0,1,0,0,1,0],
    [0,0,1,1,0,0]]
)

num_9_cp = torch.tensor(
[
    [0,1,1,1,1,0],
    [0,1,0,0,1,0],
    [0,1,0,0,1,0],
    [0,1,1,1,1,0],
    [0,0,0,0,1,0],
    [0,0,0,0,1,0]])

num_9 = torch.tensor(
[
    [0,0,0,0,0,0],
    [0,0,1,1,1,0],
    [0,0,1,0,1,0],
    [0,0,1,1,1,0],
    [0,0,0,0,1,0],
    [0,0,0,0,1,0]])


num_4 = torch.tensor(
        [
    [0,0,0,1,0,0],
    [0,0,1,1,0,0],
    [0,1,0,1,0,0],
    [1,1,1,1,1,0],
    [0,0,0,1,0,0],
    [0,0,0,1,0,0]])

In [99]:
def add_padding(img, kernel_size):
    p = kernel_size // 2
    black = [0,0,0]
    padding_img = cv2.copyMakeBorder(img, p,p,p,p, cv2.BORDER_CONSTANT, value=black)
    return padding_img

def convolution_x(img):
    kernel = np.array([-1,0,1])
    img_h, img_w = img.shape
    board = 1
    new_image = np.zeros((6,6), np.uint8)
    
    for i in range(board, img_h-board):
        for j in range(board, img_w-board):
            new_image[i-1][j-1] = np.sum(kernel * img[i, j-board:j+board+1])
    new_image = new_image.astype(np.uint8)
    return new_image/255

def convolution_y(img):
    kernel = np.transpose(np.array([-1,0,1]))
    
    img_h, img_w = img.shape
    board = 1
    new_image = np.zeros((6,6), np.uint8)
    for i in range(board, img_h-board):
        for j in range(board, img_w-board):
            new_image[i-1][j-1] = np.sum(kernel * img[i-board:i+board+1, j])
    new_image = new_image.astype(np.uint8)
    return new_image/255

def calcTangent(dx, dy):
    res = np.zeros(dx.shape, np.float)
    for i in range(6):
        for j in range(6):
            if (dx[i][j] == 0):
                if (dy[i][j] >= 0):
                    res[i][j] = 90
                else:
                    res[i][j] = 270
            else:
                res[i][j] = np.arctan(dy[i][j] / dx[i][j])
    res[res >= 90] = 1            
    return res.astype(np.uint8).flatten()
    

def calcMagnitude(dx, dy):
    res = np.sqrt(dx**2 + dy**2)
    res[res < 0.1] = 0
    return res


image_y_0 = convolution_y(add_padding(num_0.numpy().copy(),3))
image_x_0 = convolution_x(add_padding(num_0.numpy().copy(),3))
# print(image_y)
# print(image_x)

image_y_9 =  convolution_y(add_padding(num_9.numpy().copy(),3))
image_x_9 = convolution_x(add_padding(num_9.numpy().copy(),3))

image_y_9_cp =  convolution_y(add_padding(num_9_cp.numpy().copy(),3))
image_x_9_cp = convolution_x(add_padding(num_9_cp.numpy().copy(),3))

image_y_4 =  convolution_y(add_padding(num_4.numpy().copy(),3))
image_x_4 = convolution_x(add_padding(num_4.numpy().copy(),3))


# print(calcTangent(image_x,image_y))
# print(calcTangent(image_x_9_cp,image_y_9_cp))
# print("\n")
# print(calcTangent(image_x_9,image_y_9))
# print("\n")
# print(calcTangent(image_x_0,image_y_0))
# print("\n")
# print(calcTangent(image_x_4,image_y_4))
# print(calcValue(image_x_0,image_y_0))
# print(calcMagnitude(image_x_9,image_y_9))
# print(calcMagnitude(image_x_9_cp,image_y_9_cp))
# print(calcHamming(calcValue(image_x_9,image_y_9),calcValue(image_x_9_cp,image_y_9_cp).flatten()))
print(calcHamming(calcTangent(image_x_9,image_y_9), calcTangent(image_x_9_cp,image_y_9_cp)))

# print(image_x)
# print(image_y)

13


In [8]:
def slid1(m ,theta):
    feature_1, feature_2, feature_3 = 0, 0, 0
    for i in range(0,3):
        for j in range(0,3):
            if (theta[i][j] == 0):
                if (m[i][j] == 0):
                    feature_1 += 1
                else:
                    feature_1 += 2
            if (theta[i][j] == 1):
                if (m[i][j] == 0):
                    feature_2 += 1
                else:
                    feature_2 += 2
            if (theta[i][j] == 90):
                if (m[i][j] == 0):
                    feature_3 += 1
                else:
                    feature_3 += 2
    return [feature_1, feature_2, feature_3]

def slid2(m ,theta):
    feature_1, feature_2, feature_3 = 0, 0, 0
    for i in range(0,3):
        for j in range(3,6):
            if (theta[i][j] == 0):
                if (m[i][j] == 0):
                    feature_1 += 1
                else:
                    feature_1 += 2
            if (theta[i][j] == 1):
                if (m[i][j] == 0):
                    feature_2 += 1
                else:
                    feature_2 += 2
            if (theta[i][j] == 90):
                if (m[i][j] == 0):
                    feature_3 += 1
                else:
                    feature_3 += 2
    return [feature_1, feature_2, feature_3]

def slid3(m ,theta):
    feature_1, feature_2, feature_3 = 0, 0, 0
    for i in range(3,6):
        for j in range(0,3):
            if (theta[i][j] == 0):
                if (m[i][j] == 0):
                    feature_1 += 1
                else:
                    feature_1 += 2
            if (theta[i][j] == 1):
                if (m[i][j] == 0):
                    feature_2 += 1
                else:
                    feature_2 += 2
            if (theta[i][j] == 90):
                if (m[i][j] == 0):
                    feature_3 += 1
                else:
                    feature_3 += 2
    return [feature_1, feature_2, feature_3]

def slid4(m ,theta):
    feature_1, feature_2, feature_3 = 0, 0, 0
    for i in range(3,6):
        for j in range(3,6):
            if (theta[i][j] == 0):
                if (m[i][j] == 0):
                    feature_1 += 1
                else:
                    feature_1 += 2
            if (theta[i][j] == 1):
                if (m[i][j] == 0):
                    feature_2 += 1
                else:
                    feature_2 += 2
            if (theta[i][j] == 90):
                if (m[i][j] == 0):
                    feature_3 += 1
                else:
                    feature_3 += 2
    return [feature_1, feature_2, feature_3]

In [100]:
def get_feature(img):
    img_h, img_w = img.shape
    
    image = img.numpy().copy()
    dx = convolution_x(add_padding(image, 3))
    dy = convolution_y(add_padding(image, 3))
    theta = calcTangent(dx, dy)
    
#     features = []
#     features += slid1(m, theta)
#     features += slid2(m, theta)
#     features += slid3(m, theta)
#     features += slid4(m, theta)
    
    return theta

features = [get_feature(img) for img in image_data]
features

[array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=uint8),
 array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
        1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1], dtype=uint8),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
        1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1], dtype=uint8),
 array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=uint8),
 array([1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], dtype=uint8),
 array([0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=uint8),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=uint8),
 array([0, 0, 1, 1, 0, 0, 1

In [101]:
def model_calcDistance(feature):
    # 下面添加对feature进行决策的代码，判定出feature 属于[0,1,2,3,...9]哪个类别
    scores = []
    for i in range(10):
        scores.append(calcHamming(feature, features[i]))
    y = np.argmin(scores)
    return y

# def

In [102]:
if __name__=="__main__":
    
    image_data = generate_data()
    # 打印出0的图像
    print("数字0对应的图片是:")
    print(image_data[0])
    print("-"*20)
    
    # 打印出8的图像
    print("数字8对应的图片是:")
    print(image_data[8])
    print("-"*20)
    
    #对每张图片进行识别
    print("对每张图片进行识别")
    for i in range(0,10):
        x=image_data[i]
	#对当前图片提取特征
        feature=get_feature(x)
        # 对提取到得特征进行分类
        y = model_calcDistance((feature))
	#打印出分类结果
        print("图像[%s]得分类结果是:[%s],它得特征是[%s]"%(i,y,feature))

数字0对应的图片是:
tensor([[0, 0, 1, 1, 0, 0],
        [0, 1, 0, 0, 1, 0],
        [0, 1, 0, 0, 1, 0],
        [0, 1, 0, 0, 1, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0]])
--------------------
数字8对应的图片是:
tensor([[0, 0, 1, 1, 0, 0],
        [0, 1, 0, 0, 1, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 1, 0, 0, 1, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0]])
--------------------
对每张图片进行识别
图像[0]得分类结果是:[0],它得特征是[[1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1]]
图像[1]得分类结果是:[1],它得特征是[[1 1 0 1 0 1 1 0 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 1 0 0 1 1 1 1 1 1]]
图像[2]得分类结果是:[2],它得特征是[[1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 1 1 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 1 1]]
图像[3]得分类结果是:[3],它得特征是[[1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1]]
图像[4]得分类结果是:[4],它得特征是[[1 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1]]
图像[5]得分类结果是:[5],它得特征是[[0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0 1 1 1 1 1 1 1]]
图像[6]得